"""
Copyright 2020 Jerrad M. Genson

This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""

import subprocess
from pathlib import Path

import preprocess_stage1
import preprocess_stage2
import gen_model

GIT_ROOT = subprocess.check_output(['git', 'rev-parse', '--show-toplevel'])
GIT_ROOT = Path(GIT_ROOT.decode('utf-8').strip())
BUILD_DIR = GIT_ROOT / Path('build')
DATA_DIR = GIT_ROOT / Path('data')


def build_preprocess_stage1(target, source, env):
    return preprocess_stage1.main([BUILD_DIR / str(target)] + [str(s) for s in source])

preprocess_stage1_builder = Builder(action=build_preprocess_stage1,
                                    suffix='.csv',
                                    src_suffix='.data')

def build_preprocess_stage2(target, source, env):
    return preprocess_stage2.main([BUILD_DIR / str(t) for t in target] + [str(source)])

preprocess_stage2_builder = Builder(action=build_preprocess_stage1,
                                    suffix='.csv',
                                    src_suffix='.csv')

def build_gen_model(target, source, env):
    return gen_model.main([BUILD_DIR / str(target)] + [str(s) for s in source])

gen_model_builder = Builder(action=build_gen_model, suffix='.dat')

env = Environment(BUILDERS=dict(
    Preprocess_stage1: preprocess_stage1_builder,
    Preprocess_stage2: preprocess_stage2_builder,
    Gen_model: gen_model_builder,
))

env.Preprocess_stage1('combined_data',
                      [DATA_DIR / 'hungarian', DATA_DIR / 'long_beach', DATA_DIR / 'switzerland'])

env.Preprocess_stage2(['training', 'testing', 'validation'], BUILD_DIR / 'combined_data')
env.Gen_model('qdaim', [BUILD_DIR / 'training.csv',
                        BUILD_DIR / 'validation.csv',
                        SRC_DIR / 'gen_model_config.json'])
