"""
Copyright 2020 Jerrad M. Genson

This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""

Import('env')
Import('GIT_ROOT')
Import('INGESTED_DIR')
DATA_DIR = GIT_ROOT / 'data'

hungarian = env.Ingest_raw_uci_data(str(INGESTED_DIR / 'hungarian'),
                                    str(DATA_DIR / 'hungarian'))

long_beach = env.Ingest_raw_uci_data(str(INGESTED_DIR / 'long_beach'),
                                     str(DATA_DIR / 'long_beach'))

switzerland = env.Ingest_raw_uci_data(str(INGESTED_DIR / 'switzerland'),
                                      str(DATA_DIR / 'switzerland'))

cleveland = env.Ingest_cleveland_data(str(INGESTED_DIR / 'cleveland'),
                                      str(DATA_DIR / 'cleveland'))

preprocessed = env.Preprocess([hungarian, long_beach, switzerland, cleveland])
qdaim = env.Gen_model('qdaim', 'gen_model_config')
Depends(qdaim, preprocessed)
Clean(qdaim, 'gen_model_config.json')
NoClean(qdaim)
